version: '3.8'

services:
  news-bot:
    build:
      context: .
      # You could specify the Dockerfile explicitly if it wasn't named 'Dockerfile'
      # dockerfile: Dockerfile
    container_name: yahoo-news-telegram-bot
    # Load environment variables from a .env file in the same directory
    # This is generally safer for secrets than listing them directly here.
    env_file:
      - .env
    volumes:
      # Mount a local directory named 'data' into '/data' inside the container.
      # The POSTED_ARTICLES_FILE environment variable defaults to '/data/posted_articles.json'.
      # This ensures the JSON file persists across container restarts.
      # Create the './data' directory locally if it doesn't exist before running 'docker-compose up'.
      - ./data:/data
      # Optional: Mount logs if logging to a file within the container
      # - ./logs:/opt/app/logs
    # Restart policy: Restart the container unless it was explicitly stopped.
    restart: unless-stopped

# Optional: Define a named volume instead of a host mount
# volumes:
#   news_data:

# And then use it in the service:
# services:
#   news-bot:
#     ...
#     volumes:
#       - news_data:/data